import { useEffect, useState } from "react";
import { RefreshCw, Users } from "lucide-react";
import { fetchLeagueOngoingGame } from "../../api/leagueLabApi";
import { getLeagueChampionIconUrl, getLeagueProfileIconUrl } from "../../api/api";

export default function LeagueOngoingGame({ onOpenPlayer, onError }) {
  const [data,setData]=useState(null),[busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);try{setData(await fetchLeagueOngoingGame());}catch(error){onError(error?.response?.data?.detail||"实时对局读取失败");}finally{setBusy(false);}};
  useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer);},[]);
  const grouped=(data?.players||[]).reduce((out,row)=>{const key=String(row.team||"未知队伍");(out[key]??=[]).push(row);return out;},{});
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-bold"><Users className="mr-2 inline h-4 w-4"/>实时对局检测</h2><p className="mt-1 text-xs text-cs2-text-muted">读取当前 Gameflow 队伍，分析最近 20 场、当前英雄使用情况与重复同队关系。</p></div><button onClick={load} className="rounded-xl border border-cs2-border px-3 py-2 text-xs"><RefreshCw className={`mr-1 inline h-4 w-4 ${busy?"animate-spin":""}`}/>刷新</button></div>{!data?.available&&<div className="rounded-2xl border border-dashed border-cs2-border p-12 text-center text-sm text-cs2-text-muted">进入英雄选择或游戏加载阶段后自动显示十名玩家</div>}{Object.entries(grouped).map(([team,players])=><section key={team} className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated"><header className="border-b border-cs2-border px-4 py-3 text-sm font-bold">队伍 {team}</header><div className="grid gap-2 p-3 md:grid-cols-2">{players.map((player,index)=>{const recent=player.recent||{},usage=player.champion_usage||{};return <button key={player.puuid||index} onClick={()=>player.puuid&&onOpenPlayer(player.puuid)} className="flex items-center gap-3 rounded-xl border border-cs2-border-subtle p-3 text-left hover:border-emerald-400/30"><span className="relative h-11 w-11 shrink-0"><img src={getLeagueChampionIconUrl(player.champion_id)} alt={player.champion_name||"英雄"} className="h-11 w-11 rounded-lg bg-emerald-400/10 object-cover"/>{player.summoner?.profileIconId!=null&&<img src={getLeagueProfileIconUrl(player.summoner.profileIconId)} alt="召唤师头像" className="absolute -bottom-1 -right-1 h-5 w-5 rounded-full border-2 border-cs2-bg-elevated object-cover"/>}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><b className="truncate">{player.summoner?.gameName||player.champion_name}</b>{player.premade_group&&<em className="not-italic rounded bg-violet-400/15 px-1.5 py-0.5 text-[10px] font-bold text-violet-300">组排 {String.fromCharCode(64+player.premade_group)}</em>}</span><span className="mt-1 block text-[11px] text-cs2-text-muted">近 {recent.matches||0} 场胜率 {recent.matches?Math.round(recent.wins/recent.matches*100):0}% · {player.champion_name} {usage.matches||0} 场 / KDA {usage.average_kda||0}</span><span className="mt-1 block text-xs text-emerald-300">{player.tag?.label||"未添加本地标签"}</span></span></button>})}</div></section>)}</div>;
}
