import { useEffect, useState } from "react";
import { AlertTriangle, Boxes, Gift, Maximize2, Power, RefreshCw, ScrollText, Trophy, Users } from "lucide-react";
import { fetchLeagueClientWindow, fetchLeagueGameSettingsFile, fetchLeagueLabStatus, fetchLeagueOngoingGame, fetchLeagueToolkitOverview, resizeLeagueClientWindow, sendLeagueChatMessage, terminateLeagueGameClient, updateLeagueChatPresence, updateLeagueGameSettingsFile, updateLeagueRankedStatus } from "../../api/leagueLabApi";
import { buildLeagueFormPreset, buildLeaguePremadePreset } from "../../utils/leagueChatPresets";

const cards = [
  ["missions", "任务", ScrollText],
  ["unclaimed_rewards", "待处理奖励", Gift],
  ["loot", "战利品种类", Boxes],
  ["friends", "好友", Users],
];
const rankedQueues = [["RANKED_SOLO_5x5","单双排位"],["RANKED_FLEX_SR","灵活排位"],["RANKED_TFT","云顶之弈"]];
const rankedTiers = ["IRON","BRONZE","SILVER","GOLD","PLATINUM","EMERALD","DIAMOND","MASTER","GRANDMASTER","CHALLENGER"];

export default function LeagueToolkitOverview({ onError }) {
  const [data, setData] = useState(null);
  const [busy, setBusy] = useState(false);
  const [availability,setAvailability]=useState("chat");
  const [statusMessage,setStatusMessage]=useState("");
  const [rankedStatus,setRankedStatus]=useState({queue:"RANKED_SOLO_5x5",tier:"CHALLENGER",division:"I"});
  const [preset,setPreset]=useState(()=>localStorage.getItem("league-fixed-chat-preset")||"");
  const [settingsFile,setSettingsFile]=useState(null);
  const [clientWindow,setClientWindow]=useState(null);
  const [windowSize,setWindowSize]=useState({baseWidth:1280,baseHeight:720});
  const load = async () => { setBusy(true); try { const [next,status]=await Promise.all([fetchLeagueToolkitOverview(),fetchLeagueLabStatus()]);setData(next);setAvailability(next.chat_presence?.availability||"chat");setStatusMessage(next.chat_presence?.statusMessage||"");setRankedStatus(status?.settings?.ranked_status||{queue:"RANKED_SOLO_5x5",tier:"CHALLENGER",division:"I"});try{setSettingsFile(await fetchLeagueGameSettingsFile());}catch{setSettingsFile(null);}try{setClientWindow(await fetchLeagueClientWindow());}catch{setClientWindow(null);} } catch (error) { onError(error?.response?.data?.detail || "工具箱读取失败"); } finally { setBusy(false); } };
  const applyPresence=async()=>{setBusy(true);try{const next=await updateLeagueChatPresence({availability,status_message:statusMessage});setData((current)=>({...current,chat_presence:next.chat_presence}));}catch(error){onError(error?.response?.data?.detail||"聊天状态应用失败");}finally{setBusy(false);}};
  const applyRanked=async()=>{setBusy(true);try{await updateLeagueRankedStatus(rankedStatus);}catch(error){onError(error?.response?.data?.detail||"排位展示应用失败");}finally{setBusy(false);}};
  const sendPreset=async()=>{const lines=preset.split(/\r?\n/).map((line)=>line.trim()).filter(Boolean);localStorage.setItem("league-fixed-chat-preset",preset);setBusy(true);try{await sendLeagueChatMessage(lines);}catch(error){onError(error?.response?.data?.detail||"预设消息发送失败");}finally{setBusy(false);}};
  const terminateGame=async()=>{if(!window.confirm("只会结束当前前台的 League of Legends.exe。未保存的本局状态可能丢失，确定继续吗？"))return;setBusy(true);try{await terminateLeagueGameClient();}catch(error){onError(error?.response?.data?.detail||"结束游戏进程失败");}finally{setBusy(false);}};
  const toggleSettingsFile=async()=>{const mode=settingsFile?.mode==="readonly"?"writable":"readonly";setBusy(true);try{setSettingsFile(await updateLeagueGameSettingsFile(mode));}catch(error){onError(error?.response?.data?.detail||"修改游戏设置文件属性失败");}finally{setBusy(false);}};
  const resizeClient=async()=>{if(!window.confirm(`将 League 客户端内容区调整为 ${windowSize.baseWidth} × ${windowSize.baseHeight} 的缩放尺寸并居中，确定继续吗？`))return;setBusy(true);try{setClientWindow(await resizeLeagueClientWindow(Number(windowSize.baseWidth),Number(windowSize.baseHeight)));}catch(error){onError(error?.response?.data?.detail||"调整 League 客户端窗口失败");}finally{setBusy(false);}};
  const generatePreset=async(type)=>{setBusy(true);try{const game=await fetchLeagueOngoingGame();const lines=type==="premade"?buildLeaguePremadePreset(game.players||[]):buildLeagueFormPreset(game.players||[]);if(!lines.length)throw new Error(type==="premade"?"当前没有可显示的组排关系":"当前没有实时对局数据");setPreset(lines.slice(0,10).join("\n"));}catch(error){onError(error?.response?.data?.detail||error?.message||"生成消息草稿失败");}finally{setBusy(false);}};
  useEffect(() => { load(); }, []);
  return <div className="space-y-4">
    <div className="flex items-center justify-between"><div><h2 className="font-bold">League 客户端工具箱</h2><p className="mt-1 text-xs text-cs2-text-muted">读取任务、奖励、战利品与好友概况。当前阶段严格只读，不会领取、分解、兑换或删除任何内容。</p></div><button onClick={load} className="rounded-xl border border-cs2-border px-3 py-2 text-xs"><RefreshCw className={`mr-1 inline h-4 w-4 ${busy ? "animate-spin" : ""}`}/>刷新</button></div>
    <section className="grid gap-3 md:grid-cols-4">{cards.map(([key,label,Icon])=><article key={key} className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><Icon className="mb-5 h-5 w-5 text-emerald-300"/><div className="text-2xl font-bold">{data?.counts?.[key] ?? "—"}</div><div className="mt-1 text-xs text-cs2-text-muted">{label}</div></article>)}</section>
    <section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><h3 className="text-sm font-bold">进行中的任务</h3><div className="mt-3 grid gap-2">{(data?.missions||[]).slice(0,12).map((mission,index)=><div key={mission.id||index} className="rounded-xl border border-cs2-border-subtle px-3 py-2 text-xs"><b>{mission.title||mission.name||mission.id||"未命名任务"}</b><span className="ml-2 text-cs2-text-muted">{mission.status||mission.state||""}</span></div>)}{data&&!data.missions?.length&&<div className="text-xs text-cs2-text-muted">暂无可显示任务</div>}</div></section>
    <section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><h3 className="text-sm font-bold">聊天状态</h3><p className="mt-1 text-xs text-cs2-text-muted">与 LeagueAkari 相同，通过本机 LCU 修改；只有点击“应用”才会写入。</p><div className="mt-4 grid gap-3 md:grid-cols-[220px_1fr_auto]"><select value={availability} onChange={(event)=>setAvailability(event.target.value)} className="rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2.5 text-sm"><option value="chat">在线</option><option value="mobile">手机在线</option><option value="away">离开</option><option value="offline">离线</option><option value="dnd">请勿打扰</option><option value="spectating">观战中</option><option value="online">游戏在线</option></select><input value={statusMessage} onChange={(event)=>setStatusMessage(event.target.value)} maxLength={500} placeholder="自定义状态消息" className="rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2.5 text-sm outline-none"/><button onClick={applyPresence} disabled={busy||!data?.chat_presence} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold text-black disabled:opacity-40">应用</button></div></section>
    <section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><div className="flex items-start gap-3"><Trophy className="mt-0.5 h-5 w-5 text-amber-300"/><div className="min-w-0 flex-1"><h3 className="text-sm font-bold">排位展示</h3><p className="mt-1 text-xs text-cs2-text-muted">只修改聊天名片上的展示，不改变真实段位；点击应用才会写入。自动登录恢复请在“自动游戏流程”中单独开启。</p><div className="mt-4 grid gap-3 md:grid-cols-[1.4fr_1fr_100px_auto]"><select value={rankedStatus.queue} onChange={(e)=>setRankedStatus({...rankedStatus,queue:e.target.value})} className="rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2.5 text-sm">{rankedQueues.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={rankedStatus.tier} onChange={(e)=>setRankedStatus({...rankedStatus,tier:e.target.value})} className="rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2.5 text-sm">{rankedTiers.map((value)=><option key={value} value={value}>{value}</option>)}</select><select value={rankedStatus.division} disabled={["MASTER","GRANDMASTER","CHALLENGER"].includes(rankedStatus.tier)} onChange={(e)=>setRankedStatus({...rankedStatus,division:e.target.value})} className="rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2.5 text-sm disabled:opacity-40">{["I","II","III","IV"].map((value)=><option key={value} value={value}>{value}</option>)}</select><button onClick={applyRanked} disabled={busy} className="rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-bold text-black disabled:opacity-40">应用</button></div></div></div></section>
    <section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><h3 className="text-sm font-bold">房间 / 英雄选择预设消息</h3><p className="mt-1 text-xs text-cs2-text-muted">每行一条，点击后合并发送到当前 LCU 对话；不会自动发送，游戏内键盘模拟暂未启用。</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>generatePreset("form")} disabled={busy} className="rounded-lg border border-cyan-400/25 bg-cyan-400/10 px-3 py-1.5 text-xs text-cyan-200 disabled:opacity-40">生成近期表现草稿</button><button onClick={()=>generatePreset("premade")} disabled={busy} className="rounded-lg border border-violet-400/25 bg-violet-400/10 px-3 py-1.5 text-xs text-violet-200 disabled:opacity-40">生成组排关系草稿</button></div><textarea value={preset} onChange={(event)=>setPreset(event.target.value)} maxLength={3000} rows={4} placeholder="例如：大家好，祝游戏愉快" className="mt-3 w-full resize-y rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2.5 text-sm outline-none"/><div className="mt-2 flex justify-end"><button onClick={sendPreset} disabled={busy||!preset.trim()} className="rounded-xl border border-emerald-400/30 bg-emerald-400/10 px-4 py-2 text-xs font-semibold text-emerald-300 disabled:opacity-40">发送到当前对话</button></div></section>
    <section className="rounded-2xl border border-rose-400/25 bg-rose-400/[.04] p-4"><div className="flex items-center gap-3"><AlertTriangle className="h-5 w-5 text-rose-300"/><div className="min-w-0 flex-1"><h3 className="text-sm font-bold">游戏进程应急控制</h3><p className="mt-1 text-xs text-cs2-text-muted">仅当 League 游戏进程处于前台时可结束；用于卡死或无法退出，不会结束 LeagueClientUx。</p></div><button onClick={terminateGame} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-rose-400/30 bg-rose-400/10 px-4 py-2 text-xs font-semibold text-rose-200 disabled:opacity-40"><Power className="h-4 w-4"/>结束前台游戏</button></div></section>
    <section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><div className="flex items-center gap-3"><Boxes className="h-5 w-5 text-amber-300"/><div className="min-w-0 flex-1"><h3 className="text-sm font-bold">游戏设置文件保护</h3><p className="mt-1 text-xs text-cs2-text-muted">{settingsFile?`${settingsFile.file_name} 当前为${settingsFile.mode==="readonly"?"只读":"可写"}`:"连接客户端后可读取 PersistedSettings.json 属性"}；只改变文件属性，不修改文件内容。</p></div><button onClick={toggleSettingsFile} disabled={busy||!settingsFile} className="rounded-xl border border-amber-400/30 bg-amber-400/10 px-4 py-2 text-xs font-semibold text-amber-200 disabled:opacity-40">切换为{settingsFile?.mode==="readonly"?"可写":"只读"}</button></div></section>
    <section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><div className="flex flex-wrap items-center gap-3"><Maximize2 className="h-5 w-5 text-cyan-300"/><div className="min-w-[240px] flex-1"><h3 className="text-sm font-bold">LeagueClientUx 窗口修复</h3><p className="mt-1 text-xs text-cs2-text-muted">按客户端当前缩放比例重新设置外层与 CEF 内容窗口并居中。{clientWindow?` 当前约 ${clientWindow.width} × ${clientWindow.height}，缩放 ${clientWindow.zoom??"未知"}`:"请先显示 League 客户端窗口"}</p></div><label className="flex items-center gap-1 text-xs">W<input type="number" min="640" max="3840" value={windowSize.baseWidth} onChange={(event)=>setWindowSize({...windowSize,baseWidth:event.target.value})} className="w-24 rounded-lg border border-cs2-border bg-cs2-bg-input px-2 py-1.5"/></label><label className="flex items-center gap-1 text-xs">H<input type="number" min="360" max="2160" value={windowSize.baseHeight} onChange={(event)=>setWindowSize({...windowSize,baseHeight:event.target.value})} className="w-24 rounded-lg border border-cs2-border bg-cs2-bg-input px-2 py-1.5"/></label><button onClick={resizeClient} disabled={busy} className="rounded-xl border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-xs font-semibold text-cyan-200 disabled:opacity-40">调整并居中</button></div></section>
  </div>;
}
