import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Search, X } from "lucide-react";
import { fetchLeagueChampions } from "../../api/leagueLabApi";

const MODES = [["ranked","排位模式"],["aram","大乱斗类"],["arena","斗魂竞技场"],["urf","无限火力"],["clash","克隆/赛事"],["doom-bots","终极魔典/特殊"],["custom","自定义对局"],["default","其他模式"]];
const POSITIONS = [["default","通用"],["top","上路"],["jungle","打野"],["middle","中路"],["bottom","下路"],["utility","辅助"]];
const emptyPool = () => ({default:[],top:[],jungle:[],middle:[],bottom:[],utility:[]});
const emptyProfile = () => ({pick:{enabled:false,champions:emptyPool(),delay_seconds:3,ignore_intent:false,strategy:"show-and-lock-in",show_intent:true,bench_select_first_available_champion:true,bench_swap_accumulated_delay_seconds:2.5,bench_handle_trade_enabled:true},ban:{enabled:false,champions:emptyPool(),delay_seconds:3,strategy:"show-and-lock-in"}});

function Toggle({checked,onChange}) { return <button type="button" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)} className={`relative h-6 w-11 shrink-0 rounded-full ${checked?"bg-emerald-500":"bg-cs2-bg-input"}`}><span className={`absolute left-1 top-1 h-4 w-4 rounded-full bg-white transition-transform ${checked?"translate-x-5":""}`}/></button>; }

export default function LeagueChampionPriorityEditor({settings,onUpdate}) {
  const [mode,setMode]=useState("aram"),[position,setPosition]=useState("default"),[kind,setKind]=useState("pick"),[picker,setPicker]=useState(false),[search,setSearch]=useState(""),[champions,setChampions]=useState([]);
  useEffect(()=>{fetchLeagueChampions().then((data)=>setChampions(data.champions||[])).catch(()=>setChampions([]));},[]);
  const profiles=settings.auto_select_profiles||{};
  const profile=profiles[mode]||emptyProfile();
  const config=profile[kind];
  const selected=config.champions?.[position]||[];
  const byId=useMemo(()=>new Map(champions.map((item)=>[item.id,item])),[champions]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return champions.filter((item)=>!q||item.name.toLowerCase().includes(q)||item.alias.toLowerCase().includes(q)||String(item.id).includes(q));},[champions,search]);
  const patchConfig=(patch)=>onUpdate({auto_select_profiles:{...profiles,[mode]:{...profile,[kind]:{...config,...patch}}}});
  const setPool=(ids)=>patchConfig({champions:{...emptyPool(),...(config.champions||{}),[position]:ids}});
  const move=(index,delta)=>{const next=[...selected],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setPool(next);};
  return <div className="grid gap-4 lg:grid-cols-[220px_1fr]">
    <aside className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-3"><div className="mb-2 text-xs font-bold text-cs2-text-muted">生效模式</div>{MODES.map(([id,label])=><button key={id} onClick={()=>setMode(id)} className={`mb-1 w-full rounded-lg px-3 py-2 text-left text-sm ${mode===id?"bg-emerald-400/15 font-semibold text-emerald-300":"text-cs2-text-secondary hover:bg-white/5"}`}>{label}</button>)}</aside>
    <section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4">
      <div className="mb-4 flex gap-2">{[["pick","英雄选择"],["ban","英雄禁用"]].map(([id,label])=><button key={id} onClick={()=>setKind(id)} className={`rounded-lg px-4 py-2 text-xs font-semibold ${kind===id?"bg-emerald-500/15 text-emerald-300":"text-cs2-text-muted"}`}>{label}</button>)}</div>
      <div className="mb-4 flex items-center justify-between border-b border-cs2-border-subtle pb-4"><div><div className="font-semibold">启用此模式的自动{kind==="pick"?"选择":"禁用"}</div><div className="mt-1 text-xs text-cs2-text-muted">按列表顺序选择第一个当前可用英雄。</div></div><Toggle checked={config.enabled} onChange={(enabled)=>patchConfig({enabled})}/></div>
      <div className="mb-3 flex flex-wrap gap-2">{POSITIONS.map(([id,label])=><button key={id} onClick={()=>setPosition(id)} className={`rounded-lg border px-3 py-1.5 text-xs ${position===id?"border-emerald-400/40 bg-emerald-400/10 text-emerald-300":"border-cs2-border text-cs2-text-muted"}`}>{label}</button>)}</div>
      <button onClick={()=>setPicker(true)} className="mb-3 rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-xs font-semibold text-emerald-300">选择并排序英雄（{selected.length}）</button>
      <div className="space-y-1">{selected.map((id,index)=><div key={`${id}-${index}`} className="flex items-center gap-3 rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2"><span className="grid h-7 w-7 place-items-center rounded-md bg-emerald-400/10 text-xs font-bold text-emerald-300">{byId.get(id)?.name?.slice(0,1)||id}</span><span className="min-w-0 flex-1 truncate text-sm">{byId.get(id)?.name||`英雄 ${id}`}</span><button onClick={()=>move(index,-1)} aria-label="上移"><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(index,1)} aria-label="下移"><ArrowDown className="h-4 w-4"/></button><button onClick={()=>setPool(selected.filter((_,i)=>i!==index))} aria-label="移除"><X className="h-4 w-4 text-red-300"/></button></div>)}</div>
      <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs text-cs2-text-muted">执行延迟（秒）<input type="number" min="0" max="15" step="0.5" value={config.delay_seconds} onChange={(e)=>patchConfig({delay_seconds:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"/></label><label className="text-xs text-cs2-text-muted">锁定策略<select value={config.strategy} onChange={(e)=>patchConfig({strategy:e.target.value})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"><option value="just-show">仅亮出</option><option value="show-and-lock-in">亮出后延迟锁定</option><option value="lock-in-immediately">延迟后直接锁定</option></select></label></div>
      {kind==="pick"&&<div className="mt-4 grid gap-2 text-sm">{[["show_intent","提前预选"],["ignore_intent","忽略队友预选冲突"],["bench_select_first_available_champion","优先选择备战席"],["bench_handle_trade_enabled","自动处理英雄交换请求"]].map(([key,label])=><div key={key} className="flex items-center justify-between rounded-lg border border-cs2-border px-3 py-2"><span>{label}</span><Toggle checked={Boolean(config[key])} onChange={(value)=>patchConfig({[key]:value})}/></div>)}<label className="text-xs text-cs2-text-muted">备战席最短累积等待（秒）<input type="number" min="0" max="15" step="0.1" value={config.bench_swap_accumulated_delay_seconds} onChange={(e)=>patchConfig({bench_swap_accumulated_delay_seconds:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"/></label></div>}
    </section>
    {picker&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/65 p-6" onMouseDown={()=>setPicker(false)}><div className="grid max-h-[78vh] w-full max-w-3xl grid-cols-2 overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-page shadow-2xl" onMouseDown={(e)=>e.stopPropagation()}><div className="border-r border-cs2-border p-4"><div className="mb-3 flex items-center gap-2 rounded-lg border border-cs2-border bg-cs2-bg-input px-3"><Search className="h-4 w-4 text-cs2-text-muted"/><input autoFocus value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="搜索英雄" className="w-full bg-transparent py-2.5 text-sm outline-none"/></div><div className="max-h-[60vh] overflow-y-auto">{filtered.map((champion)=><button key={champion.id} onClick={()=>!selected.includes(champion.id)&&setPool([...selected,champion.id])} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm ${selected.includes(champion.id)?"text-emerald-300":"hover:bg-white/5"}`}><span className="grid h-7 w-7 place-items-center rounded-md bg-white/5 text-xs">{champion.name.slice(0,1)}</span>{champion.name}</button>)}</div></div><div className="p-4"><div className="mb-3 flex items-center justify-between"><div className="font-semibold">已选 {selected.length} 项</div><button onClick={()=>setPicker(false)}><X className="h-5 w-5"/></button></div><div className="max-h-[60vh] space-y-1 overflow-y-auto">{selected.map((id,index)=><div key={`${id}-${index}`} className="flex items-center gap-2 rounded-lg bg-white/5 px-3 py-2 text-sm"><span className="flex-1">{byId.get(id)?.name||id}</span><button onClick={()=>move(index,-1)}><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(index,1)}><ArrowDown className="h-4 w-4"/></button><button onClick={()=>setPool(selected.filter((_,i)=>i!==index))}><X className="h-4 w-4"/></button></div>)}</div></div></div></div>}
  </div>;
}
