import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Keyboard, Plus, Save, Send, Trash2 } from "lucide-react";
import { sendLeagueInGamePreset } from "../../api/leagueLabApi";

const createPresetId = () => `preset_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;

export default function LeagueInGamePresetTools({ settings, busy, onSettingsUpdate, onBusyChange, onError }) {
  const [items,setItems]=useState(settings?.in_game_fixed_presets||[]);
  useEffect(()=>setItems(settings?.in_game_fixed_presets||[]),[settings?.in_game_fixed_presets]);
  const enabled=Boolean(settings?.toolkit_account_actions_enabled&&settings?.in_game_send_enabled);
  const persist=async(next)=>{onBusyChange(true);try{await onSettingsUpdate({in_game_fixed_presets:next});setItems(next);}catch(error){onError(error?.response?.data?.detail||"保存游戏内预设失败");}finally{onBusyChange(false);}};
  const patchItem=(id,patch)=>setItems((current)=>current.map((item)=>item.id===id?{...item,...patch}:item));
  const add=()=>persist([...items,{id:createPresetId(),title:"未命名预设",shortcut:null,content:""}]);
  const remove=(id)=>{if(window.confirm("删除这条固定文字预设？"))persist(items.filter((item)=>item.id!==id));};
  const move=(id,offset)=>{const index=items.findIndex((item)=>item.id===id),target=index+offset;if(index<0||target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];persist(next);};
  const send=async(id)=>{if(window.prompt("该操作会向当前房间、英雄选择或前台游戏聊天发送预设内容。\n请输入“我确认发送”继续：")!=="我确认发送")return;onBusyChange(true);try{await sendLeagueInGamePreset(id,"manual","我确认发送");}catch(error){onError(error?.response?.data?.detail||"发送预设失败");}finally{onBusyChange(false);}};
  const toggle=async(value)=>{if(value&&!window.confirm("启用后，已配置快捷键的固定文字预设可在软件驻留后台时发送；只有房间、英雄选择或前台英雄联盟游戏阶段会执行。确定启用吗？"))return;await onSettingsUpdate({in_game_send_enabled:value});};
  const saveGeneratedShortcut=(kind,target,value)=>{const key=`in_game_${kind}_shortcuts`;return onSettingsUpdate({[key]:{friendly:null,enemy:null,all:null,...(settings?.[key]||{}),[target]:String(value||"").trim()||null}});};

  return <section className="rounded-2xl border border-indigo-400/20 bg-cs2-bg-elevated p-4">
    <div className="flex flex-wrap items-center gap-3"><Keyboard className="h-4 w-4 text-indigo-300"/><div className="mr-auto"><h3 className="text-sm font-bold">游戏内固定文字预设</h3><p className="mt-1 text-xs text-cs2-text-muted">房间/选人阶段通过 LCU 发送；游戏中逐行输入前会逐次确认前台进程。预设和快捷键默认关闭。</p></div><button role="switch" aria-label="启用游戏内预设发送" aria-checked={Boolean(settings?.in_game_send_enabled)} disabled={!settings?.toolkit_account_actions_enabled||busy} onClick={()=>toggle(!settings?.in_game_send_enabled)} className={`relative h-6 w-11 rounded-full ${settings?.in_game_send_enabled?"bg-indigo-500":"bg-cs2-bg-input"} disabled:opacity-40`}><span className={`absolute left-1 top-1 h-4 w-4 rounded-full bg-white transition-transform ${settings?.in_game_send_enabled?"translate-x-5":""}`}/></button></div>
    <div className="mt-3 flex flex-wrap items-center gap-2"><label className="text-xs text-cs2-text-muted">逐行间隔 <input aria-label="逐行发送间隔" type="number" min="100" max="5000" value={settings?.in_game_send_interval_ms||250} disabled={!settings?.toolkit_account_actions_enabled||busy} onChange={(event)=>onSettingsUpdate({in_game_send_interval_ms:Number(event.target.value)})} className="ml-1 w-20 rounded-lg border border-cs2-border bg-cs2-bg-input px-2 py-1.5"/> ms</label><button disabled={!settings?.toolkit_account_actions_enabled||busy||items.length>=100} onClick={add} className="ml-auto inline-flex items-center gap-1 rounded-lg border border-indigo-400/25 bg-indigo-400/10 px-3 py-1.5 text-xs text-indigo-200 disabled:opacity-40"><Plus className="h-3.5 w-3.5"/>新增预设</button><button disabled={!settings?.toolkit_account_actions_enabled||busy} onClick={()=>persist(items)} className="inline-flex items-center gap-1 rounded-lg border border-cs2-border px-3 py-1.5 text-xs disabled:opacity-40"><Save className="h-3.5 w-3.5"/>保存全部</button></div>
    <div className="mt-3 space-y-2">{items.map((item,index)=><article key={item.id} className="grid gap-2 rounded-xl border border-cs2-border-subtle p-3 lg:grid-cols-[180px_160px_1fr_auto]"><input aria-label={`预设标题 ${item.id}`} value={item.title} maxLength={64} onChange={(event)=>patchItem(item.id,{title:event.target.value})} placeholder="预设标题" className="rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-xs"/><input aria-label={`预设快捷键 ${item.id}`} value={item.shortcut||""} maxLength={80} onChange={(event)=>patchItem(item.id,{shortcut:event.target.value.trim()||null})} placeholder="可选，如 Ctrl+Alt+H" className="rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-xs"/><textarea aria-label={`预设内容 ${item.id}`} value={item.content} maxLength={65536} rows={2} onChange={(event)=>patchItem(item.id,{content:event.target.value})} placeholder="每行一条，最多发送前 10 行" className="resize-y rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-xs"/><div className="flex items-center gap-1"><button aria-label={`上移 ${item.title}`} disabled={busy||index===0} onClick={()=>move(item.id,-1)} className="rounded-lg border border-cs2-border p-2 disabled:opacity-30"><ArrowUp className="h-3.5 w-3.5"/></button><button aria-label={`下移 ${item.title}`} disabled={busy||index===items.length-1} onClick={()=>move(item.id,1)} className="rounded-lg border border-cs2-border p-2 disabled:opacity-30"><ArrowDown className="h-3.5 w-3.5"/></button><button aria-label={`发送 ${item.title}`} disabled={!enabled||busy||!item.content.trim()} onClick={()=>send(item.id)} className="rounded-lg border border-emerald-400/25 bg-emerald-400/10 p-2 text-emerald-200 disabled:opacity-40"><Send className="h-3.5 w-3.5"/></button><button aria-label={`删除 ${item.title}`} disabled={busy} onClick={()=>remove(item.id)} className="rounded-lg border border-rose-400/25 bg-rose-400/10 p-2 text-rose-200 disabled:opacity-40"><Trash2 className="h-3.5 w-3.5"/></button></div></article>)}{!items.length&&<div className="rounded-xl border border-dashed border-cs2-border p-6 text-center text-xs text-cs2-text-muted">尚未创建固定文字预设</div>}</div>
    <div className="mt-4 border-t border-cs2-border-subtle pt-4"><h4 className="text-xs font-bold">分析预设目标快捷键</h4><p className="mt-1 text-[11px] text-cs2-text-muted">按键时读取最新十人数据，并分别生成近期表现、组排或打野画像。留空即关闭。</p><div className="mt-3 grid gap-2 lg:grid-cols-3">{[["rating","近期表现"],["premade","组排关系"],["jungle","打野画像"]].map(([kind,label])=><div key={kind} className="rounded-xl border border-cs2-border-subtle p-3"><b className="text-xs">{label}</b>{[["friendly","己方"],["enemy","敌方"],["all","双方"]].map(([target,targetLabel])=><label key={target} className="mt-2 grid grid-cols-[42px_1fr] items-center gap-2 text-[11px] text-cs2-text-muted"><span>{targetLabel}</span><input aria-label={`${label}${targetLabel}快捷键`} defaultValue={settings?.[`in_game_${kind}_shortcuts`]?.[target]||""} maxLength={80} disabled={!settings?.toolkit_account_actions_enabled||busy} onBlur={(event)=>saveGeneratedShortcut(kind,target,event.target.value)} placeholder="未设置" className="rounded-lg border border-cs2-border bg-cs2-bg-input px-2 py-1.5 font-mono text-xs disabled:opacity-40"/></label>)}</div>)}</div></div>
  </section>;
}
