import { useCallback, useEffect, useMemo, useState } from "react";
import { Boxes, CheckCircle2, Gamepad2, History, MonitorUp, RefreshCw, ShieldCheck, SlidersHorizontal, Swords, UserRoundSearch, Users, WifiOff } from "lucide-react";
import { invoke } from "@tauri-apps/api/core";
import { fetchLeagueLabStatus, fetchLeagueMatches, runLeagueLabAction, saveLeagueLabSettings } from "../api/leagueLabApi";
import LeagueChampionPriorityEditor from "../components/league/LeagueChampionPriorityEditor";
import LeagueChampionLoadoutEditor from "../components/league/LeagueChampionLoadoutEditor";
import LeaguePlayerCenter from "../components/league/LeaguePlayerCenter";
import LeagueOngoingGame from "../components/league/LeagueOngoingGame";
import LeagueToolkitOverview from "../components/league/LeagueToolkitOverview";

const DEFAULT_SETTINGS = { automation_enabled:false, auto_accept_enabled:false, auto_accept_delay_seconds:1, play_again_enabled:false, auto_reconnect_enabled:false, invitation_strategy:"ignore", auto_handle_invitations_enabled:false, reject_invitation_when_away:false, invitation_handling_strategies:{}, auto_skip_leader_enabled:false, auto_select_enabled:false, auto_pick_champion_ids:[], auto_ban_champion_ids:[], auto_select_profiles:{}, champion_action_delay_seconds:1, champion_lock_in:true, auto_champion_config_enabled:false, champion_loadouts:[], auto_honor_enabled:false, auto_honor_strategy:"prefer-lobby-member", auto_matchmaking_enabled:false, auto_matchmaking_delay_seconds:5, auto_matchmaking_minimum_members:1, auto_matchmaking_wait_for_invitees:true, auto_matchmaking_rematch_strategy:"never", auto_matchmaking_rematch_fixed_duration:120, auto_reply_enabled:false, auto_reply_only_away:false, auto_reply_text:"", lock_offline_status:false, auto_send_aram_team_side_enabled:false, auto_send_aram_team_side_visible_to_team:false, auto_invite_friend_puuids:[], mini_enabled:true, mini_auto_show:true, respawn_timer_enabled:false };

function Switch({ title, description, checked, onChange, children }) {
  return <div className="flex min-h-[70px] items-center gap-4 border-b border-cs2-border-subtle px-4 py-3 last:border-b-0"><div className="min-w-0 flex-1"><div className="text-sm font-semibold text-cs2-text-primary">{title}</div><div className="mt-1 text-xs leading-5 text-cs2-text-muted">{description}</div></div>{children}<button type="button" role="switch" aria-label={title} aria-checked={checked} onClick={() => onChange(!checked)} className={`relative h-6 w-11 shrink-0 appearance-none rounded-full p-0 transition-colors duration-150 active:scale-[.97] ${checked ? "bg-emerald-500" : "bg-cs2-bg-input"}`}><span className={`absolute left-1 top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform duration-150 ${checked ? "translate-x-5" : "translate-x-0"}`} /></button></div>;
}

function Field({ label, value, onChange, placeholder }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-cs2-text-secondary">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2.5 text-sm text-cs2-text-primary outline-none transition-colors focus:border-emerald-400/50" /></label>; }

export default function LeagueAutomationLabPage() {
  const [status,setStatus]=useState(null),[settings,setSettings]=useState(DEFAULT_SETTINGS),[busy,setBusy]=useState(false),[error,setError]=useState(""),[tab,setTab]=useState("flow"),[matches,setMatches]=useState([]),[playerPuuid,setPlayerPuuid]=useState("");
  const [pickIdsText,setPickIdsText]=useState(""),[banIdsText,setBanIdsText]=useState("");
  const load=useCallback(async()=>{try{const next=await fetchLeagueLabStatus();setStatus(next);setSettings({...DEFAULT_SETTINGS,...(next.settings||{})});setError("");}catch(e){setError(e?.response?.data?.detail||"无法读取英雄联盟客户端状态");}},[]);
  useEffect(()=>{load();const timer=setInterval(load,3000);return()=>clearInterval(timer);},[load]);
  useEffect(()=>{if(tab!=="champion"){setPickIdsText(settings.auto_pick_champion_ids.join(", "));setBanIdsText(settings.auto_ban_champion_ids.join(", "));}},[settings.auto_pick_champion_ids,settings.auto_ban_champion_ids,tab]);
  const update=async(patch)=>{const next={...settings,...patch};setSettings(next);setBusy(true);try{setStatus(await saveLeagueLabSettings(next));setError("");}catch(e){setError(e?.response?.data?.detail||"设置保存失败");await load();}finally{setBusy(false);}};
  const loadMatches=async()=>{setBusy(true);try{const data=await fetchLeagueMatches(20);setMatches(data.matches||[]);setError("");}catch(e){setError(e?.response?.data?.detail||"战绩读取失败");}finally{setBusy(false);}};
  useEffect(()=>{if(tab==="history")loadMatches();},[tab]);
  const connected=Boolean(status?.connected), tabs=useMemo(()=>[{id:"flow",label:"游戏流程",icon:SlidersHorizontal},{id:"champion",label:"英雄与配置",icon:Swords},{id:"history",label:"我的战绩",icon:History},{id:"players",label:"玩家中心",icon:UserRoundSearch},{id:"ongoing",label:"实时对局",icon:Users},{id:"toolkit",label:"客户端工具",icon:Boxes}],[]);
  return <div className="mx-auto w-full max-w-[1220px] space-y-5 overflow-y-auto px-7 py-7">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-emerald-400/25 bg-emerald-400/10 px-2.5 py-1 text-[11px] font-bold uppercase tracking-[.16em] text-emerald-300"><Gamepad2 className="h-3.5 w-3.5"/> League Automation Lab</div><h1 className="text-2xl font-bold tracking-[-.03em] text-cs2-text-primary">英雄联盟实验室</h1><p className="mt-1 text-sm text-cs2-text-secondary">连接 LeagueClientUx，自动处理对局流程并直接查看本机账号战绩。</p></div><div className="flex gap-2"><button onClick={()=>invoke("open_league_mini")} className="inline-flex items-center gap-2 rounded-xl border border-cs2-border px-3 py-2 text-xs font-semibold text-cs2-text-secondary active:scale-[.97]"><MonitorUp className="h-4 w-4"/> 打开 Mini 面板</button><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-cs2-border px-3 py-2 text-xs font-semibold text-cs2-text-secondary active:scale-[.97]"><RefreshCw className={`h-4 w-4 ${busy?"animate-spin":""}`}/> 重新检测</button></div></header>
    <section className={`rounded-2xl border p-4 ${connected?"border-emerald-400/30 bg-emerald-400/[.07]":"border-amber-400/30 bg-amber-400/[.06]"}`}><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${connected?"bg-emerald-400/15 text-emerald-300":"bg-amber-400/15 text-amber-300"}`}>{connected?<CheckCircle2 className="h-5 w-5"/>:<WifiOff className="h-5 w-5"/>}</span><div className="flex-1"><div className="font-semibold text-cs2-text-primary">{connected?`已连接：${status?.summoner_name||"League Client"}`:"尚未检测到英雄联盟客户端"}</div><div className="mt-1 text-xs text-cs2-text-muted">{connected?`阶段：${status?.phase||"Unknown"} · ${status?.platform_id||status?.region||"本地区服"}`:"支持 WeGame/Tencent 与 Riot 客户端；请先完成登录。"}</div></div>{status?.last_action&&<div className="text-right text-xs text-emerald-300"><div>最近操作</div><div className="mt-1 font-semibold">{status.last_action}</div></div>}</div></section>
    {error&&<div className="rounded-xl border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm text-red-300">{error}</div>}
    <nav className="flex w-fit rounded-xl border border-cs2-border bg-cs2-bg-elevated p-1">{tabs.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-semibold transition-colors ${tab===id?"bg-emerald-400/15 text-emerald-300":"text-cs2-text-muted hover:text-cs2-text-primary"}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav>
    {tab==="flow"&&<section className="overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-elevated"><Switch title="复活计时器" description="游戏进行中通过本机 Live Client Data 在 Mini 显示死亡复活倒计时；默认关闭。" checked={settings.respawn_timer_enabled} onChange={(v)=>update({respawn_timer_enabled:v})}/></section>}
    {tab==="flow"&&<><section className="overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-elevated"><Switch title="启用英雄联盟自动化" description="总开关；关闭时只读取状态和战绩。" checked={settings.automation_enabled} onChange={(v)=>update({automation_enabled:v})}/><Switch title="自动接受对局" description="进入 ReadyCheck 后按设定延迟接受。" checked={settings.auto_accept_enabled} onChange={(v)=>update({auto_accept_enabled:v})}><label className="flex items-center gap-2 text-xs text-cs2-text-muted">延迟<input type="number" value={settings.auto_accept_delay_seconds} onChange={(e)=>update({auto_accept_delay_seconds:Number(e.target.value)})} className="w-16 rounded-lg border border-cs2-border bg-cs2-bg-input px-2 py-1.5"/>秒</label></Switch><Switch title="自动点赞" description="结算时按所选策略处理点赞。" checked={settings.auto_honor_enabled} onChange={(v)=>update({auto_honor_enabled:v})}><select value={settings.auto_honor_strategy} onChange={(e)=>update({auto_honor_strategy:e.target.value})} className="rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2 text-xs"><option value="prefer-lobby-member">优先房间队友</option><option value="only-lobby-member">仅房间队友</option><option value="all-member">所有队友</option><option value="all-member-including-opponent">包含对手</option><option value="opt-out">自动跳过</option></select></Switch><Switch title="自动返回房间" description="结算完成后通过 LCU 返回房间。" checked={settings.play_again_enabled} onChange={(v)=>update({play_again_enabled:v})}/><Switch title="自动重新连接" description="进入 Reconnect 阶段后尝试重新连接。" checked={settings.auto_reconnect_enabled} onChange={(v)=>update({auto_reconnect_enabled:v})}/><div className="flex min-h-[70px] items-center gap-4 px-4 py-3"><div className="flex-1"><div className="text-sm font-semibold">房间邀请策略</div><div className="mt-1 text-xs text-cs2-text-muted">接受、拒绝或保持不处理。</div></div><select value={settings.invitation_strategy} onChange={(e)=>update({invitation_strategy:e.target.value})} className="rounded-xl border border-cs2-border bg-cs2-bg-input px-3 py-2 text-xs"><option value="ignore">不处理</option><option value="accept">自动接受</option><option value="decline">自动拒绝</option></select></div></section><div className="grid gap-3 md:grid-cols-3">{[["accept","立即接受"],["play-again","返回房间"],["reconnect","立即重连"]].map(([action,label])=><button key={action} disabled={!connected||busy} onClick={()=>runLeagueLabAction(action)} className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4 text-left text-sm font-semibold transition-colors hover:border-emerald-400/30 active:scale-[.98] disabled:opacity-40">{label}</button>)}</div></>}
    {tab==="flow"&&<section className="overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-elevated"><Switch title="Mini 面板" description="创建独立 Mini；关闭 Mini 只隐藏当前阶段，进入下一阶段后可再次自动显示。" checked={settings.mini_enabled} onChange={(v)=>update({mini_enabled:v})}/><Switch title="Mini 按阶段自动显示" description="在房间、匹配、接受对局和非观战英雄选择阶段自动弹出，其余阶段自动隐藏。" checked={settings.mini_auto_show} onChange={(v)=>update({mini_auto_show:v})}/><Switch title="自动转交房主" description="自己是房主时优先转交给已准备的队员。" checked={settings.auto_skip_leader_enabled} onChange={(v)=>update({auto_skip_leader_enabled:v})}/><Switch title="按队列自动处理邀请" description="读取邀请的 inviteGameType，按下方默认或专用策略处理。" checked={settings.auto_handle_invitations_enabled} onChange={(v)=>update({auto_handle_invitations_enabled:v})}/><Switch title="离开状态不接受邀请" description="League 聊天状态为 away 时暂停处理邀请。" checked={settings.reject_invitation_when_away} onChange={(v)=>update({reject_invitation_when_away:v})}/><div className="grid gap-3 p-4 md:grid-cols-3"><label className="text-xs text-cs2-text-muted">默认策略<select value={settings.invitation_handling_strategies?.["<DEFAULT>"]||settings.invitation_strategy} onChange={(e)=>update({invitation_strategy:e.target.value,invitation_handling_strategies:{...(settings.invitation_handling_strategies||{}),"<DEFAULT>":e.target.value}})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"><option value="ignore">不处理</option><option value="accept">接受</option><option value="decline">拒绝</option></select></label>{[["NORMAL_GAME","匹配/排位"],["CUSTOM_GAME","自定义对局"]].map(([key,label])=><label key={key} className="text-xs text-cs2-text-muted">{label}<select value={settings.invitation_handling_strategies?.[key]||"ignore"} onChange={(e)=>update({invitation_handling_strategies:{...(settings.invitation_handling_strategies||{}),[key]:e.target.value}})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"><option value="ignore">不处理</option><option value="accept">接受</option><option value="decline">拒绝</option></select></label>)}</div></section>}
    {tab==="flow"&&<section className="overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-elevated"><Switch title="自动开始匹配" description={`满足房主、人数、邀请和惩罚条件后倒计时开始匹配；当前：${status?.matchmaking_status||"idle"}`} checked={settings.auto_matchmaking_enabled} onChange={(v)=>update({auto_matchmaking_enabled:v})}/><Switch title="等待邀请中的队员" description="仍有 Pending 邀请时不自动开始匹配。" checked={settings.auto_matchmaking_wait_for_invitees} onChange={(v)=>update({auto_matchmaking_wait_for_invitees:v})}/><div className="grid gap-3 p-4 md:grid-cols-4"><label className="text-xs text-cs2-text-muted">开始延迟（秒）<input type="number" min="0" max="60" value={settings.auto_matchmaking_delay_seconds} onChange={(e)=>update({auto_matchmaking_delay_seconds:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"/></label><label className="text-xs text-cs2-text-muted">最低人数<input type="number" min="1" max="5" value={settings.auto_matchmaking_minimum_members} onChange={(e)=>update({auto_matchmaking_minimum_members:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"/></label><label className="text-xs text-cs2-text-muted">停止/重排策略<select value={settings.auto_matchmaking_rematch_strategy} onChange={(e)=>update({auto_matchmaking_rematch_strategy:e.target.value})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"><option value="never">永不</option><option value="fixed-duration">固定时长</option><option value="estimated-duration">预计队列时长</option></select></label><label className="text-xs text-cs2-text-muted">固定时长（秒）<input type="number" min="10" value={settings.auto_matchmaking_rematch_fixed_duration} onChange={(e)=>update({auto_matchmaking_rematch_fixed_duration:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-cs2-border bg-cs2-bg-input px-3 py-2 text-sm"/></label></div></section>}
    {tab==="flow"&&<section className="overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-elevated"><Switch title="自动回复私聊" description="收到新的私聊消息时发送预设内容；默认关闭以避免误发。" checked={settings.auto_reply_enabled} onChange={(v)=>update({auto_reply_enabled:v})}/><Switch title="仅离开状态回复" description="只有聊天状态为 away 时才自动回复。" checked={settings.auto_reply_only_away} onChange={(v)=>update({auto_reply_only_away:v})}/><Switch title="锁定离线状态" description="客户端尝试恢复在线时重新设为 offline。" checked={settings.lock_offline_status} onChange={(v)=>update({lock_offline_status:v})}/><Switch title="大乱斗阵营提示" description="在 ARAM/海克斯大乱斗英雄选择中自动提示蓝方或红方。" checked={settings.auto_send_aram_team_side_enabled} onChange={(v)=>update({auto_send_aram_team_side_enabled:v})}/><Switch title="阵营提示对队友可见" description="关闭时使用本地 celebration 类型；开启后发送普通队伍聊天。" checked={settings.auto_send_aram_team_side_visible_to_team} onChange={(v)=>update({auto_send_aram_team_side_visible_to_team:v})}/><div className="grid gap-3 p-4 md:grid-cols-2"><Field label="自动回复内容" value={settings.auto_reply_text} onChange={(value)=>update({auto_reply_text:value})} placeholder="例如：正在游戏，稍后回复"/><Field label="等待上线后自动邀请的好友 PUUID" value={(settings.auto_invite_friend_puuids||[]).join(", ")} onChange={(value)=>update({auto_invite_friend_puuids:String(value).split(/[,，\s]+/).filter(Boolean).slice(0,20)})} placeholder="多个 PUUID 用逗号分隔；邀请成功后自动移除"/></div></section>}
    {tab==="champion"&&<div className="space-y-4"><section className="overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-elevated"><Switch title="自动英雄选择/禁用" description="按游戏模式、分路与英雄优先级执行 LeagueAkari 等价的预选、锁定、备战席和交换流程。" checked={settings.auto_select_enabled} onChange={(v)=>update({auto_select_enabled:v})}/></section><LeagueChampionPriorityEditor settings={settings} onUpdate={update}/><section className="rounded-2xl border border-cs2-border bg-cs2-bg-elevated p-4"><Switch title="自动配置符文与召唤师技能" description="英雄确认后应用对应的本地配置。" checked={settings.auto_champion_config_enabled} onChange={(v)=>update({auto_champion_config_enabled:v})}/><LeagueChampionLoadoutEditor loadouts={settings.champion_loadouts} onChange={(champion_loadouts)=>update({champion_loadouts})} onError={setError}/></section></div>}
    {tab==="history"&&<section className="space-y-3"><div className="flex justify-between"><div><h2 className="font-bold">最近战绩</h2><p className="mt-1 text-xs text-cs2-text-muted">直接读取当前登录账号的 LCU 战绩，无需打开其他软件。</p></div><button onClick={loadMatches} className="rounded-xl border border-cs2-border px-3 py-2 text-xs">刷新战绩</button></div>{matches.map((m)=><article key={m.game_id} className={`grid grid-cols-[5px_1fr_auto] overflow-hidden rounded-2xl border border-cs2-border bg-cs2-bg-elevated ${m.win?"border-emerald-400/20":"border-rose-400/20"}`}><div className={m.win?"bg-emerald-400":"bg-rose-400"}/><div className="p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/5 text-sm font-bold">{m.champion_id}</span><div><div className="font-bold">{m.champion_name} · {m.win?"胜利":"失败"}</div><div className="mt-1 text-xs text-cs2-text-muted">{m.game_mode} · {m.played_at||"时间未知"}</div></div></div></div><div className="flex items-center gap-6 p-4 text-right"><div><div className="font-mono text-lg font-bold">{m.kills}/{m.deaths}/{m.assists}</div><div className="text-[11px] text-cs2-text-muted">K / D / A</div></div><div><div className="font-mono text-sm font-bold">{m.damage}</div><div className="text-[11px] text-cs2-text-muted">英雄伤害</div></div></div></article>)}{!busy&&matches.length===0&&<div className="rounded-2xl border border-dashed border-cs2-border p-12 text-center text-sm text-cs2-text-muted">连接客户端后即可读取最近战绩</div>}</section>}
    {tab==="players"&&<LeaguePlayerCenter currentPuuid={playerPuuid||status?.current_summoner?.puuid||""} onError={setError}/>}
    {tab==="ongoing"&&<div className="space-y-3"><div className="flex justify-end"><button onClick={()=>invoke("open_league_ongoing")} className="inline-flex items-center gap-2 rounded-xl border border-cs2-border px-3 py-2 text-xs font-semibold"><MonitorUp className="h-4 w-4"/>独立实时对局窗口</button></div><LeagueOngoingGame onError={setError} onOpenPlayer={(puuid)=>{setPlayerPuuid(puuid);setTab("players");}}/></div>}
    {tab==="toolkit"&&<LeagueToolkitOverview onError={setError}/>}
    <div className="flex items-start gap-3 rounded-2xl border border-cs2-border-subtle bg-cs2-bg-elevated/60 p-4 text-xs leading-5 text-cs2-text-muted"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/><p>功能通过本机 League LCU 完成；认证令牌只保存在进程内存，不写入配置、不上传。自动操作受游戏版本和区服接口变动影响，首次使用建议先关闭自动锁定观察一局。</p></div>
  </div>;
}
